@startuml
!include <c4/C4_Context.puml>  

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

'LAYOUT_WITH_LEGEND

title System Context diagram for Portfolio Management App

Person(customer  , Customer , "<$user> <$mobile_user>\n A member of the investment club" )

System(portfolio_app, "Portfolio app", "Allows customers to view portfolio information about their stocks.")

System_Ext(identity_management, "Identity management", "The AWS Identity management Cognito.")
System_Ext(payment_management, "Payment Management", "The Payment Platform Stripe.")
System_Ext(dns_management, "Domain Management", "The DNS Route53 Platform")
System_Ext(finance_platform, "Finance Platform", "The Yahoo Finance Platform.")
System_Ext(database, "Database System", "Stores all of the core portfolio about members, stocks, etc.")

Rel(customer, portfolio_app, "Uses")

Rel(portfolio_app, identity_management, "Uses")
Rel(portfolio_app, payment_management, "Uses")
Rel(portfolio_app, dns_management, "Uses")
Rel(portfolio_app, finance_platform, "Uses")
Rel(portfolio_app, database, "Uses")

@enduml